# fly.toml app configuration file generated for openai-service on 2023-12-11T20:04:58Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "openai-service"
primary_region = "lhr"

[build]

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 256
